# Generated by Django 4.2.7 on 2024-03-30 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pay2u', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cashback',
            options={'verbose_name': 'Кэшбэк'},
        ),
        migrations.AlterModelOptions(
            name='notification',
            options={'verbose_name': 'Сообщение', 'verbose_name_plural': 'Сообщения'},
        ),
        migrations.AlterModelOptions(
            name='payments',
            options={'verbose_name': 'Платёж', 'verbose_name_plural': 'Платежи'},
        ),
        migrations.AlterModelOptions(
            name='rate',
            options={'verbose_name': 'Тариф', 'verbose_name_plural': 'Тарифы'},
        ),
        migrations.AlterModelOptions(
            name='services',
            options={'verbose_name': 'Сервис', 'verbose_name_plural': 'Сервисы'},
        ),
        migrations.AlterModelOptions(
            name='subscription',
            options={'verbose_name': 'Подписка', 'verbose_name_plural': 'Подписки'},
        ),
        migrations.AlterModelOptions(
            name='usersubscription',
            options={'verbose_name': 'Ваша подписка', 'verbose_name_plural': 'Ваши подписки'},
        ),
    ]
