const services = [
    {
        id: 0,
        name: "litres",
        title: "ЛитРес",
        info: "От 199 ₽ за 1 месяц",
        cashback: 10,
        image: "./images/logos/LitRes.png",
    },
    {
        id: 1,
        name: "megogo",
        title: "Megogo",
        info: "От 199 ₽ за 1 месяц",
        cashback: 10,
        image: "./images/logos/Megogo.png",
    },
    {
        id: 2,
        name: "ivi",
        title: "Иви",
        info: "От 199 ₽ за 1 месяц",
        cashback: 10,
        image: "./images/logos/Ivi.png",
    },
    {
        id: 3,
        name: "mybook",
        title: "My book",
        info: "От 199 ₽ за 1 месяц",
        cashback: 10,
        image: "./images/logos/MyBook.png",
    },
    {
        id: 4,
        name: "okko",
        title: "Okko",
        info: "От 199 ₽ за 1 месяц",
        cashback: 10,
        image: "./images/logos/Okko.png",
    },
    {
        id: 5,
        name: "storytel",
        title: "Storytel",
        info: "От 199 ₽ за 1 месяц",
        cashback: 10,
        image: "./images/logos/Storytel.png",
    },
    {
        id: 6,
        name: "spotify",
        title: "Spotify",
        info: "От 199 ₽ за 1 месяц",
        cashback: 10,
        image: "./images/logos/Spotify.png",
    },
    {
        id: 7,
        name: "yandexplus",
        title: "Яндекс плюс",
        info: "От 199 ₽ за 1 месяц",
        cashback: 10,
        image: "./images/logos/YandexPlus.png",
    },
];

export default services;
